### ISSUE TITLE
In FF, scroll bar flashes each time an input is made.

### ISSUE THREAD

**Issue by nomosyn** [javierjulio/textarea-autosize#15]
I was typing nonsense stuff in the textarea and window's scrollbar begin to flash each time I typed in stuff.
The scroll bar can be seen on the far right of the screen.

![screen shot 2015-07-11 at 23 45 24](https://cloud.githubusercontent.com/assets/2693150/8635535/30ca691a-2827-11e5-9e26-0029f72afdfd.png)

**Comment by javierjulio** [comment]
Yes I believe this is occurring due to a solution I put in, in response to an issue reported where the textarea doesn't stay in the right place if in a scrollable container other than the body element. This seems to have caused some more issues so I will remove it and see about another solution.

**Comment by javierjulio** [comment]
Actually what I thought it was, was wrong. It is just a side effect of how the plugin works. Thanks though for bringing it to my attention as I hadn't noticed it.
