### ISSUE TITLE
bug: border size is not accounted for

### ISSUE THREAD

**Issue by kulbakin** [javierjulio/textarea-autosize#18]
It appears height calculation does no account for border width resulting in slight size increase glitch upon first key input. The cause is that suggested `box-sizing: border-box;` style does include border width. The suggested fix is to make `diff` variable to account for border as well:

```js
      var diff = parseInt(this.$element.css('paddingBottom')) +
                 parseInt(this.$element.css('paddingTop')) +
                 parseInt(this.$element.css('borderTopWidth')) +
                 parseInt(this.$element.css('borderBottomWidth')) || 0;
```

**Comment by javierjulio** [comment]
Awesome thanks! I've been trying to get the project to build again but running into several dependency issues. 😩 First libsass couldn't be found but then uninstalling gulp-sass and reinstalling now seems to be causing more failures. I'm not really sure at this point what's exactly wrong.

At this point I think I'm just going to drop a lot of the dev deps and stick to normal scripts, no gulp. Been more of a pain. Sorry. I'll try to get this out ASAP. Thanks!

**Comment by alexkravets** [comment]
+1
