### ISSUE TITLE
Bootstrap 4 demo

### ISSUE THREAD

**Issue by djibe** [javierjulio/textarea-autosize#23]
H guys, here is a demo for using textarea autosize with Bootstrap 4 (and Material design kit by Daemonite).
enjoy it here : https://jsfiddle.net/djibe89/bofcrp8v/

**Comment by Erutan409** [comment]
Are there supposed to be unused vertical scrollbars..?

**Comment by djibe** [comment]
@Erutan409 It happens in large and small textareas but I can't figure out how to fix it yet.

**Comment by djibe** [comment]
@Erutan409 Fixed with overflow-y: hidden;
Fiddle updated

**Comment by clayclayclay** [comment]
@djibe  the demo url can't be accessed, please check it?

**Comment by djibe** [comment]
> 
> 
> @djibe the demo url can't be accessed, please check it?

Hi, it works perfectly for me from work. Tried another browser, internet access, PC ?

**Comment by clayclayclay** [comment]
@djibe  Hi, there was something wrong with my network, now it's okay, thx.

**Comment by djibe** [comment]
Hi, sorry I didn't close this Issue earlier !

For those who want a BS4 intergration: <https://djibe.github.io/material/docs/4.6/plugins/textarea-autosize/>

**Comment by javierjulio** [comment]
No worries at all, thanks! Just cleaning up as been meaning to come back to this to rewrite it. Just looked at that page and like what you put together!

**Comment by djibe** [comment]
Glad you are back !
Merry Christmas
