### ISSUE TITLE
Placing textarea at a lower point in the document causes scrolling issues

### ISSUE THREAD

**Issue by fmal** [javierjulio/textarea-autosize#6]
See: http://jsfiddle.net/nh90hvhe/1/

When you type some lines of text, the size of the textarea grows longer than the browser window. At that point the top of the window jumps to the top of the textarea every time a key is pressed, which is extremely annoying for the user.

**Comment by alexkravets** [comment]
I'm having this issue with the latest 0.4.0 version in Chrome. When window is scrolled on a keyup event it's just scrolled to the top, parent div is absolutely positioned in full height.

**Comment by alexkravets** [comment]
Here is solution that works for me, this includes standalone scrollParent plugin (https://github.com/slindberg/jquery-scrollparent):

        var $scrollParent = $(this).scrollParent();
        var currentScrollPosition = $scrollParent.scrollTop();

        $(this)
          .height(0)
          .height(this.scrollHeight - diff);

        $scrollParent.scrollTop(currentScrollPosition);

Posting it here in case someone needs a working solution asap.

**Comment by maxnowack** [comment]
+1

**Comment by KristerV** [comment]
in my case the height(0) causes the screen to jump and scroll to the cursor out of the view if textarea is higher than screen. Si I removed it.

**Comment by d2a-raudenaerde** [comment]
I added a .focus() at the end, seems to help my scrolling problems in IE.

      this.$element.on('input keyup isselectedbyuser', function(event) {

    	if ($(this).height()!=this.scrollHeight - diff) 
    	{
        $(this)
          .height(0)
          .height(this.scrollHeight - diff).focus();
    	}
    	
      });

**Comment by AndiZ23** [comment]
I replicate this issue when the textarea is at the bottom of a scrollable document. The page got scrolled to the top everytime when the textarea's size is changed. 
But I fixed that with `scrollIntoView(false)` under `input` and `keyup` event listener:

~~~~
$("textarea").on("input keyup", function () {
      var $bottom = $(this).next();  // there should be an element under the textarea, otherwise, use $(this)
      $bottom[0].scrollIntoView(false);
 });
~~~~
For Chrome, just using `keyup` is fine, while for IE 11, using `input` as well will prevent the document from being flashing when a key is pressed into this textarea.
